// <auto-generated />
using System;
using GrapheneTrace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrapheneTrace.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251031115249_moveContactAreaPeakPressureToChunk")]
    partial class moveContactAreaPeakPressureToChunk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GrapheneTrace.Areas.Identity.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DataId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AlertId");

                    b.HasIndex("DataId");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Diagnostics", b =>
                {
                    b.Property<int>("DiagnosticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DiagnosticsId");

                    b.HasIndex("DataId")
                        .IsUnique();

                    b.ToTable("Diagnostics");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ChunkId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.FeedbackReply", b =>
                {
                    b.Property<int>("feedbackReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("feedbackReplyId");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackReply");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Heatmap", b =>
                {
                    b.Property<int>("HeatmapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeatmapId");

                    b.HasIndex("DataId")
                        .IsUnique();

                    b.ToTable("Heatmap");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.HeatmapChunk", b =>
                {
                    b.Property<int>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChunkData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkNumber")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ContactAreaPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("HeatmapId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PeakPressureIndex")
                        .HasColumnType("REAL");

                    b.HasKey("ChunkId");

                    b.HasIndex("HeatmapId");

                    b.ToTable("HeatmapChunk");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.PatientClinician", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PatientId", "ClinicianId");

                    b.HasIndex("ClinicianId");

                    b.ToTable("PatientClinician");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.SensorData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DataId");

                    b.HasIndex("UserId");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Alert", b =>
                {
                    b.HasOne("GrapheneTrace.Models.Database.SensorData", "SensorData")
                        .WithMany("Alerts")
                        .HasForeignKey("DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorData");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Diagnostics", b =>
                {
                    b.HasOne("GrapheneTrace.Models.Database.SensorData", "SensorData")
                        .WithOne("Diagnostics")
                        .HasForeignKey("GrapheneTrace.Models.Database.Diagnostics", "DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorData");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Feedback", b =>
                {
                    b.HasOne("GrapheneTrace.Models.Database.HeatmapChunk", "HeatmapChunk")
                        .WithMany("Feedback")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("Feedback")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeatmapChunk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.FeedbackReply", b =>
                {
                    b.HasOne("GrapheneTrace.Models.Database.Feedback", "Feedback")
                        .WithMany("Replies")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany("FeedbackReplies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Heatmap", b =>
                {
                    b.HasOne("GrapheneTrace.Models.Database.SensorData", "SensorData")
                        .WithOne("Heatmap")
                        .HasForeignKey("GrapheneTrace.Models.Database.Heatmap", "DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorData");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.HeatmapChunk", b =>
                {
                    b.HasOne("GrapheneTrace.Models.Database.Heatmap", "Heatmap")
                        .WithMany("Chunks")
                        .HasForeignKey("HeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heatmap");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.PatientClinician", b =>
                {
                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", "Clinician")
                        .WithMany("PatientLinks")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", "Patient")
                        .WithMany("ClinicianLinks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.SensorData", b =>
                {
                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GrapheneTrace.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrapheneTrace.Areas.Identity.Data.ApplicationUser", b =>
                {
                    b.Navigation("ClinicianLinks");

                    b.Navigation("Feedback");

                    b.Navigation("FeedbackReplies");

                    b.Navigation("PatientLinks");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Feedback", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.Heatmap", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.HeatmapChunk", b =>
                {
                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("GrapheneTrace.Models.Database.SensorData", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Diagnostics");

                    b.Navigation("Heatmap");
                });
#pragma warning restore 612, 618
        }
    }
}
